trying to catch build errors in heroku compile script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -114,12 +114,16 @@ export CACHE_DIR
 export BUILD_DIR
 
 echo "-----> Starting build"
-curl -O https://beta.quicklisp.org/quicklisp.lisp
-sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql:add-to-init-file)'
 case $CL_IMPL in
-  sbcl) sh $CL_DIR/sbcl-1.3.10-x86-64-linux/run-sbcl.sh --load "$BUILDPACK_DIR/setup/compile.lisp";;
+  sbcl) sh $CL_DIR/sbcl-1.3.10-x86-64-linux/run-sbcl.sh --script "$BUILDPACK_DIR/setup/compile.lisp";;
   ccl) $CCL_DEFAULT_DIRECTORY/scripts/ccl64 -l "$BUILDPACK_DIR/setup/compile.lisp";;
 esac
 echo "-----> Build finished"
+
+return_code = $?
+if [ $return_code != 0 ]; then
+    printf "Build error: %d" $return_code
+    exit $return_code
+fi
 
 chmod a+x $BUILD_DIR/lispapp
